algolia:
  tacit_appId: 
  tacit_apiKey: 
  indexes:
    blog:
      prod: Amp-RetailStorefront.blog-production
      staging: Amp-RetailStorefront.blog-staging
    ruleBased:
      prod: Amp-RetailStorefront.rule-based-production
      staging: Amp-RetailStorefront.rule-based-staging
    productListSearch:
      prod: prod_willow_products
app:
  appName: amp-rsa
  publishStage: production
  scope: amplience-presales
analytics:
  ga:
    trackingId: 
    enabled: false
cms:
  contentBaseUri: https://amp-rsa.amplience.com
  contentApi: amprsa.cdn.content.amplience.net
  stagingName: 1kwj9tiju6tgz16c4lq8hs7n9r
  stagingApi: 1kwj9tiju6tgz16c4lq8hs7n9r.staging.bigcontent.io
  trustedHostSuffixes:
    - .cdn.content.amplience.net
    - .staging.bigcontent.io
  accountName: amprsa
  hubName: Amp-RetailStorefront
  productImageHubName: willow
  imageBasePath: cdn.media.amplience.net
  clientId: 155a793c-a3e3-4c56-928c-61d39dedad04
  clientSecret: 187ea860b199970c4e62881f58acf295e42915d5715aa0fab11167967a8dd53d
  hubId: 602d62974cedfd00014d5359
  content:
    sampleBlogId: null
dam:
    username:
    password:
    source:
    type: s3
    bucket: demo-dam-assets-amp-rsa
    region: eu-west-3
commercetools:
  authUrl: https://auth.europe-west1.gcp.commercetools.com
  apiUrl: https://api.europe-west1.gcp.commercetools.com
  projectKey: anyafinn
  clientId: 
  clientSecret: 
  defaultScopes:
    - view_products:anyafinn
    - view_categories:anyafinn
    - view_published_products:anyafinn
    - create_anonymous_token:anyafinn
  defaultFacets:
    - type: standard
      field: variants.attributes.color.label.en
      title: Color
    - type: standard
      field: variants.attributes.designer.key
      title: Designer
    - type: standard
      field: variants.attributes.size
      title: Size
    - type: standard
      field: variants.attributes.style.key
      title: Style
dynamicyield:
  apiKey: 
personify:
  personifyApi: 
  active: true
serverless:
  accessKeyId:
  secretAccessKey:
  customProfileName: 
  provider:
    stage: dev
    region: eu-west-3